apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-web-deployment
  template:
    metadata:
      labels:
        app: django-web-deployment
    spec:
      containers:
      - name: django-web-deployment
        image: registry.digitalocean.com/web-deployment:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: django-web-env
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: django-web

---

appVersion: v1
kind: Service
metadata:
  name: django-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-web-deployment
