name: Django CI

on:
  workflow_call:
  workflow_dispatch:
  push:
#    branches: [ "main" ]
    branches: [ "*" ]
  pull_request:
#    branches: [ "main" ]
    branches: [ "*" ]

jobs:
  django_build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: django_docker/
    env:
      DJANGO_SECRET_KEY: nxjahdoNKX5SHSi154asx
      POSTGRES_DB: django_docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retires 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test